services:
  - type: web
    name: nadius-api
    env: node
    region: frankfurt
    buildCommand: tsc && node dist/index.js
    startCommand: node dist/index.js
    watchForFileChanges: true
    rootDirectory: ./src